version: "3"
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.8
    environment:
      xpack.security.enabled: "false"
    volumes:
      - ./kafka-elasticsearch.docker.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - kafka
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: "false"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.8
    ports:
      - "5601:5601"
    environment:
      xpack.security.enabled: "false"
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch

